/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-19 15:24:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.header;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/header/header.css\">\r\n");
      out.write("    <title>main</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <header\r\n");
      out.write("      id=\"\"\r\n");
      out.write("      class=\"u-header u-header__sticky-top u-header--toggle-section u-header--change-appearance\"\r\n");
      out.write("      style=\"margin-top: 0px\"\r\n");
      out.write("    >\r\n");
      out.write("      <!-- PC 탑바 레이아웃 1-1 -->\r\n");
      out.write("      <div\r\n");
      out.write("        class=\"u-header__section u-header__section--hidden u-header__section--dark g-bg-white g-transition-0_3 g-pt-10--sm g-pb-0\"\r\n");
      out.write("      >\r\n");
      out.write("        <div class=\"g-hidden-xs-down\">\r\n");
      out.write("            <!-- 탑바 레이아웃 3 -->\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row-head flex-md-row justyfy-content-between\">\r\n");
      out.write(" \r\n");
      out.write("              <!-- 탑바 right 5-2 -->\r\n");
      out.write("              <div class=\"col-auto g-pos-rel g-px-15\">\r\n");
      out.write("                <ul class=\"ul list-inline g-mt-minus-10\">\r\n");
      out.write("                  <li class=\"list-inline-item\"><a class=\"g-color-topbar\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login/login.jsp\">로그인</a></li>\r\n");
      out.write("                  <li class=\"list-inline-item g-color-topbar\">|</li>\r\n");
      out.write("                  <li class=\"list-inline-item\"><a class=\"g-color-topbar\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/join/join.jsp\">회원가입</a></li>\r\n");
      out.write("                  <li class=\"list-inline-item g-color-topbar\">|</li>\r\n");
      out.write("                  <li class=\"list-inline-item\"><a class=\"g-color-topbar\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/mypage_all.jsp\">마이페이지</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 모바일 -->\r\n");
      out.write("      <div></div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 헤더 local nav bar -->\r\n");
      out.write("      <!-- 로고 -->\r\n");
      out.write("      <div class=\"container container-header header justyfy-content-between\">\r\n");
      out.write("      <div class=\"header-logo\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mainpage/main.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/header/logo.svg\" style=\"width: 240px; height: 60px;\" alt=\"\" class=\"logo\"></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- 목차 -->\r\n");
      out.write("      <div class=\"header-menu mouseover\" data-animaion-in=\"fadeIn\" data-animation-out=\"fadeOut\">\r\n");
      out.write("        <ul class=\"ul mouseover\">\r\n");
      out.write("          <li class=\"list-inline-header\">\r\n");
      out.write("            <a href=\"\"style=\"text-decoration:none; \">소개</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"list-inline-header\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lostpet/LostPet.jsp\"style=\"text-decoration:none; \">실종동물찾기</a>\r\n");
      out.write("\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"list-inline-header\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/faq/faq.jsp\"style=\"text-decoration:none; \">전문가FAQ</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"list-inline-header\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/new-list.jsp\"style=\"text-decoration:none; \">커뮤니티</a>\r\n");
      out.write("\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("<!--     <div class=\"lnb-bg showmenu\"> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"small-header\">\r\n");
      out.write("   	<a href=\"\"style=\"text-decoration:none; \">소개</a>\r\n");
      out.write("   	<a href=\"\"style=\"text-decoration:none; \">실종동물찾기</a>\r\n");
      out.write("   	<a href=\"\"style=\"text-decoration:none; \">전문가FAQ</a>\r\n");
      out.write("   	<a href=\"\"style=\"text-decoration:none; \">커뮤니티</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      $(window).load(function(){\r\n");
      out.write("          $(function() {\r\n");
      out.write("              $('.showmenu').hide();\r\n");
      out.write("              $('.mouseover').hover(function() {\r\n");
      out.write("                  $('.showmenu').slideDown();\r\n");
      out.write("              }\r\n");
      out.write("            //  , function() {\r\n");
      out.write("            //    $('.showmenu').slideUp();\r\n");
      out.write("           // }\r\n");
      out.write("              );\r\n");
      out.write("           });\r\n");
      out.write("      });\r\n");
      out.write("      </script>\r\n");
      out.write("      \r\n");
      out.write("      <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
