/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-20 01:43:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>마이페이지</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/mypage.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"header-wrap\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"topImageSection\" style=\"height:250px;\">\r\n");
      out.write("                <div class=\"img_div\"> \r\n");
      out.write("                    <img src=\"https://prodkrsahsitappadminblob.blob.core.windows.net/2019-01-singleimage-production/279d2ded-3e88-4cc5-8e9b-d8638c3b35ee-일시후원2019.png\" id=\"ctl00_topImage\" style=\"min-width:1000px; height:250px; cursor:pointer;\" onclick=\"move2TopImageLink()\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"logo_img\">\r\n");
      out.write("                    <h1 id=\"logoImg\" class=\"logo_title\">\r\n");
      out.write("                        <a href=\"\" style=\"padding-bottom: 95px; padding-left: 20px; cursor:pointer\"><img src=\"logo.png\" class=\"logo\" alt=\"스트릿애니멀파인더\" style=\"min-height: 60px; max-height:60px;\" title=\"스트릿애니멀파인더\"></a>\r\n");
      out.write("                    </h1>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_bottom\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"mypage-menu\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <ul class=\"menu-wrap\">\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/Userupdateprofile.jsp\">내 프로필 보기</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/Userupdate.jsp\">회원정보 수정</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/Userupdatepw.jsp\">비밀번호 변경</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/Userdeluser.jsp\">회원 탈퇴</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <h2 class=\"tit\">\r\n");
      out.write("        <span id=\"modi\" class=\"my-tit\">프로필 수정</span>\r\n");
      out.write("    </h2>\r\n");
      out.write("\r\n");
      out.write("    <h3 class=\"sub-tit\">\r\n");
      out.write("        <span id=\"modi\" class=\"my-tit\">스애파 프로필과 별명을 수정 하실 수 있습니다.</span>\r\n");
      out.write("    </h3>\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"change-form\">\r\n");
      out.write("        <form action=\"\">\r\n");
      out.write("            <table class=\"modi-table1\">\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr class=\"modi-table-tr\">\r\n");
      out.write("                        <th class=\"modi-table-th\" scope=\"row\">\r\n");
      out.write("                            <span class=\"col1-sp\">\r\n");
      out.write("                                프로필 사진\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <td class=\"modi-table-td\">\r\n");
      out.write("                            <div class=\"modi-item\">\r\n");
      out.write("                                <div class=\"photo_box\">\r\n");
      out.write("                                    <img src=\"https://static.nid.naver.com/images/web/user/default.png?type=s160\" width=\"100\" height=\"100\" id=\"img_source\">\r\n");
      out.write("                                    <span class=\"mask\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"btn_area\">\r\n");
      out.write("                                    <span class=\"btn_file\">\r\n");
      out.write("                                        <label for=\"inputImage\" class=\"btn-in-form\">사진변경</label>\r\n");
      out.write("                                        <input type=\"file\" id=\"inputImage\" name=\"profileImage\" accept=\"image/*\" style=\"display:none\">\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <a href=\"#\" class=\"btn-in-form\" style=\"margin-left: 8px; text-decoration: none;\">삭제</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr class=\"modi-table-tr\">\r\n");
      out.write("                        <th class=\"modi-table-th\">\r\n");
      out.write("                            <span class=\"col1-sp\">별명</span>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <td class=\"modi-table-td\">\r\n");
      out.write("                            <div class=\"modi-item\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"nickname\" id=\"inputNick\"> &nbsp;\r\n");
      out.write("                                12글자까지 입력할 수 있습니다.\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"vertical-align: bottom; text-align: center; padding-bottom:10px\">\r\n");
      out.write("                <input type=\"submit\" name=\"leave_btn\" id=\"leave_btn\" value=\"적용\" class=\"btn-custom\">\r\n");
      out.write("                <input type=\"submit\" name=\"cancel_btn\" id=\"leave_cancel_btn\" value=\"취소\" class=\"btn-custom\" style=\"background-color: #ffffff; color:black\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-wrap\">\r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div class=\"footer_link\">\r\n");
      out.write("                <span class=\"footer_btn\">\r\n");
      out.write("                    <a href=\"#\">로그아웃</a> &nbsp;&nbsp;\r\n");
      out.write("                    <b>|</b> &nbsp;&nbsp;\r\n");
      out.write("                </span>\r\n");
      out.write("                <span class=\"footer_btn\">\r\n");
      out.write("                    <a style=\"cursor:pointer;\" href=\"#\">개인정보 처리방침</a>\r\n");
      out.write("                </span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer_container\">\r\n");
      out.write("                <div class=\"footer_div\">\r\n");
      out.write("                    <a href=\"#\" style=\"cursor: pointer;\"><img src=\"https://prodkrsahsitappadminblob.blob.core.windows.net/2019-02-singleimage-production/60d8b13b-edb6-4734-bd54-4a36fe355762-푸터_카라.gif\" class=\"footer_img\" style=\"cursor:default; max-width:100%;min-width:1000px\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
